### ISSUE TITLE
Team Woe (William and Joe) - Team Prototype 3

### ISSUE THREAD

**Issue by Willler** [jdespland-teaching/CART315_2020#16]
Here is the link to the WEBGL build on itch.io: https://joeske.itch.io/teamprototype3

Please fullscreen the game so that you can see the UI and the full game.

**Comment by Willler** [comment]
Here are William's Playtest Questions. Please be as thorough or as concise as you wish.

a. How quickly did you realize that your health was also tied to killing enemies?

b. Did the amount of health gained per kill justify the level of aggression from enemies, in your opinion?

c. Did you feel like you needed a clearer indication of progress to enjoy the game, or was the current U.I good enough?

d. Do you think this type of game benefits from having a single "indicator" rather than multiple sources of information like HP, Enemies Killed, Time Spent Alive, and etc?

**Comment by tiffhc** [comment]
Hi William and Joe, is it possible to get a link to the repository where this game is on github?
I have to leave my feedback on your game's issue page.

**Comment by Willler** [comment]
Certainly. Here is the link: https://github.com/LastEndConductor/Team_Prototype3

**Comment by Cadere** [comment]
a. It was fairly obvious, though I took me a while to realise I had a weapon and could kill ennemies.
b. I think a little bit more starting health or a little bit less damage from ennemies might help, or maybe some sort of other ability like a shield or something.
c. The current U.I. was good enough
d. multiple indicators would also be fun, I think this can go both ways

Joe's Questions:
a. I feel under attack, but not in a bad way.
b. Yes, because I 1 shot them and they don't 1 shot me. But I don't feel stronger than the whole group.
c. Not necessarily, though I feel a bigger variety of abilities unlocked through time would make it more interesting to continue playing.

**Comment by madslads** [comment]
PlayTester - Madison H

_William's Questions_
a. It was so chaotic trying to stay alive that I didn't realize that
b. It seemed like the enemies had so much aggression just at the start 
c. I feel like a clearer indication of progress would have helped, maybe something to do with the characters gun shooting faster 
d. I think that it is best that this game only has a single indicator because it would be too hard to try and pay attention to anything else

_Joe's Questions_
- I feel in control of the gun? yes. Of my life? no
- I feel much slower and weaker than my enemies
- The game feels pretty unfair since it starts off with you in the center, and things are being fired at you from 4 different sides. I feel like it should start with less enemies and slowly gain more as you progress in the game. It's just way too chaotic at the start.

**Comment by miwamiwa** [comment]
a. How quickly did you realize that your health was also tied to killing enemies?
 Couldn't tell! Too focused on staying alive to even look at that corner of the screen. Would be easier for a noob like me if that info was in my face

b. Did the amount of health gained per kill justify the level of aggression from enemies, in your opinion?
Nothing justifies such violence, you should check out our game where we play with dogs and give them treats. 
Forreal yes I think so, it's challenging enough to make you think about the way you move about.  

c. Did you feel like you needed a clearer indication of progress to enjoy the game, or was the current U.I good enough?
I want to feel like a champion so maybe a timer or a kill counter would be nice to keep track of high score. HP felt more like a survival thing than progress.

d. Do you think this type of game benefits from having a single "indicator" rather than multiple sources of information like HP, Enemies Killed, Time Spent Alive, and etc?
Yes and no, less information can be easier to follow sometimes but I think the visual design aspect has more impact on how the indicators benefit the game

Joe's Questions:

Do you feel in control ?
A few minutes in, yes. At first I feel like I'm getting rekt

Do you feel stronger than your enemies ?
Ouf. Not really in the end because keeping up demands so much focus, eventually I run out.
With some downtimes that could probably change though

Does the game feel unfair ?
Yes. For the baddies. They're all like "nyaah, nyaah"
Fair/unfair I guess depends on how much time and focus you wanted to spend on this. If I had stopped after 1 minute, I would have said it feels unfair. Probably because of it being not so obvious how I'm supposed to move forward. I stopped playing once I got the hang of it because I felt like I achieved what there was to achieve, but a highscore would probably have kept me playing for a bit. Took me about 5 minutes

**Comment by NPhuongHao** [comment]
a. How quickly did you realize that your health was also tied to killing enemies? --> The health was partially hidden from the screen so I actually didn't even pay attention to the health bar...

b. Did the amount of health gained per kill justify the level of aggression from enemies, in your opinion? --> Pretty reasonable yes.

c. Did you feel like you needed a clearer indication of progress to enjoy the game, or was the current U.I good enough? --> I think in terms of UI there's not really anything to be added, as the gameplay is classic.

d. Do you think this type of game benefits from having a single "indicator" rather than multiple sources of information like HP, Enemies Killed, Time Spent Alive, and etc? --> Mostly to make players feel a sense of achievement, and stay with game longer. Usually, if there's a collection to fulfill, players will go to complete it before they call it quit.


Do you feel in control ? --> Pretty much, yes, though the constant spawning of enemies from all direction adds a good kind of chaotic feel.

Do you feel stronger than your enemies ? --> It's more a game of tenacity than raw power, so the longer you go the weaker you get... 

Does the game feel unfair ? --> I wouldn't say it feels unfair. However, a gradual increase in difficulty until it becomes ridiculously impossible to play would be appreciated.
