### ISSUE TITLE
TheMuffinWilds (Madison Hunt and Gordon Gray) [Prototype 3]

### ISSUE THREAD

**Issue by Gmangray4** [jdespland-teaching/CART315_2020#17]
If your up for a challenge then you've come to the right place! 

**Goal:** reach the end of the obstacle course.

HTML Link to Prototype 3:
https://hybrid.concordia.ca/g_gray/prototype3/Game/index.html?fbclid=IwAR2eLhhZ3HOP0RurmNBsOW8VVvcmlO_P7YXvf3k_qJVnBUZJY3JoMF-_XM0

Link to our team repository: 
https://github.com/Gmangray4/Cart315-TheMuffinWilds

**Questions:**
1) What are your initial thoughts of the prototype?

2) Were you able to reach the end of the level? 

3) How do you feel about the controls? 

4) What do you think of the prototype’s Aesthetics? 

5) What aspects of the prototype displease you? 

6) What’s your favorite thing about the prototype? 

7) Were you ever captured by the AI Head? Did you even notice a big head chasing you? 

8) Did you come up with any strategies/exploits to beat the level? 

9) Did you ever get trapped in the level? As in stuck within a wall and could not continue for example? 

10) Is there anything you would like to change in the prototype? 

11) Any final thoughts you would like to add toward the prototype?

**Comment by LastEndConductor** [comment]
1- music was very loud and distracting.
2- no.
3- camera sensitivity was way too high, didn't understand the point of the WASD, rotating the player didn't seem to make any difference.
4- the outside of the track was cool, the track was too bright.
5- mostly the music and the color of the track. 
6- the sliding.
7- no.
8- no.
9- no.
10- the camera speed.
11- cool idea, very unfriendly, I couldn't look at that red path for too long.

**Comment by Harout77** [comment]
1. Bring back memory of Super Mario 64 Penguin slide level! 
2. No, too hard to control!
3. There was a way to control the character? i couldn't move and the robot was just sliding randomly!
4. Loved the music!

**Comment by Cadere** [comment]
1. Funny chaotic aesthetic, though I did notice the leftover default Probuilder texture :P

2. No, the camera was too weird and the controls too unresponsive, inevitably I would slide off without being able to change my course because changing direction took too long or I would get stuck with my mouse in a corner and unable to change my camera more and then fall off because I couldn't see.

3. The idea of slow controls to add difficulty is interesting, but the response time was too slow and the controls felt unresponsive. Additionally when restarting the level the speed and direction was the same as when I died, so whether I got off to a good start or not was quite random.

4. The backgroud is a bit too texture heavy compared to the track. Additionally, the shadows are too dark compared and it makes it difficult to see where you're going at times.

5. The control response time was too slow and I was mostly unable to go where I wanted.

6. The colors

7. I saw it at some point but was never captured and thought I had to catch it myself.

8. Try to jump off the edges and hope to land somewhere useful

9. At one point I fell into the mountains and didn't respawn.

10. If the controls were more responsive and the camera followed the direction the character is looking it, it might be possible to reach the end.

**Comment by miwamiwa** [comment]
What are your initial thoughts of the prototype?
First thing that came to mind was it's gonna be like that mario party bobsleigh minigame woop
Camera controls are hard to decypher, I always get caught in weird angles and have a hard time focusing the cam in front of me. Anyway it's still fun sliding around the path and the world around. 

Were you able to reach the end of the level?
no.

How do you feel about the controls?
player controls felt fine, but i was challenged by the cam controls 

What do you think of the prototype’s Aesthetics?
Random but nice. Music hits the mood 

What aspects of the prototype displease you?
Ze camera. Maybe a bit linear, things like a speed boost could break the rhythm a bit.

What’s your favorite thing about the prototype?
Sliding around the background

Were you ever captured by the AI Head? Did you even notice a big head chasing you?
Alas I only noticed the bodyless fellow once, and did not see it moving

Did you come up with any strategies/exploits to beat the level?
Ouf no I came up with ways to see in front of me sometimes. But it looked like jumping from one track to another was possible. I wasn't too sure which way to go though

Did you ever get trapped in the level? As in stuck within a wall and could not continue for example?
Yeah, often.

Is there anything you would like to change in the prototype?
Fun powerups, different types of ground

Any final thoughts you would like to add toward the prototype?
It's super peaceful watching the guy slide down the track as I write these comments

**Comment by NPhuongHao** [comment]
What are your initial thoughts of the prototype? --> "Holy doughnut this will be fun."

Were you able to reach the end of the level? --> ...After a while I don't even know where I'm going.

How do you feel about the controls? --> I feel like the total control of my life is lost.

What do you think of the prototype’s Aesthetics? --> It's actually enjoyable. 

What aspects of the prototype displease you? --> That I don't know how to change my direction. Like I thought I got it, but after a while, I didn't, and... well, I got myself on an endless red space and I'm not sure if it was the way I started or somewhere else.

What’s your favorite thing about the prototype? --> The fact that I don't know where to go and I can keep going forever............

Were you ever captured by the AI Head? Did you even notice a big head chasing you? --> .... I ran toward it in the first place because I thought it was where I needed to go.

Did you come up with any strategies/exploits to beat the level? --> After a while just treated it like an open-world.........

Did you ever get trapped in the level? As in stuck within a wall and could not continue for example?--> Given my comments thus far I would say yes?

Is there anything you would like to change in the prototype? --> An ambient change would be interesting, like, the sun rises and sets repeatedly as if you're trapped in a groundhog day...

Any final thoughts you would like to add toward the prototype? --> I'm surprisingly hooked up....
