### ISSUE TITLE
Team Macey, Eugene and Hazel

### ISSUE THREAD

**Issue by weavingmemories** [jdespland-teaching/CART315_2020#18]
**WEBGL Build link:**

https://weavingmemories.itch.io/team-prototype-3

*For some reason, there's a build glitch with the pickups- they don't always disappear immediately upon clicking!*

**Group Repository:**

https://github.com/weavingmemories/CART-315-Team-Repository

**Controls:**

* Regular navigation (W A S D controls, mouse to look around, space to jump)
* Left click to throw a light / pick up an object.

**Macey's Questions:**

1. Is each section of the map well differentiated enough that you are able to generally situate where you are?

2. How did the hallways feel to navigate?

3. When you spotted a section of wall that stood out to you, did you think that there was possibly a way in/some way to interact with the scene?

**Comment by Cadere** [comment]
**Eugene's Questions:**
1. Did you find hitting the switches with the glowing balls easy or difficult? How so?
2. Did the switches convey to you that you needed to hit them?
3. When you saw something that seemed different or unusual, did you try to throw something at it?

**Comment by HazelThexton** [comment]
Hazel's Questions:

1. Did you use the minimap to navigate the environment?
2. When you changed floors, was it clear that the layout had changed?
3. Was there anything unclear about the map?

**Comment by Harout77** [comment]
1. Hitting the switch with the glowing ball was easy but not helpful to get a clue what happened, any changes or where to go. 
2. The room change was clear after going up the stairs.
3. The mini-map was clear but not that helpful since I was still lost and didn't know where to go (second level) unless if that's the most I can go, not clear!
4. The only change I notice was the door to the second level open and that door opening when hitting the switch.

**Comment by M33-Melissa** [comment]
Macey's questions:
1. I feel like the mini-map helps, but not on the first playthrough. The fact that the mini-map would rotate with the player made it difficult to re-situate yourself If you stop looking at it for a moment and just walked in the maze. On my second run I ended up looking at the mini-map almost exclusively to direct myself and stopped to interact with the buttons indicated in the mini-map.

2. As a maze is, the hallways all look the same so only based on that it's difficult to situate yourself. But they are clear to navigate through. 

3. Yeah I thought that If I threw a light at the "switch" it would turn green and open the white door to collect the cube. Since the first one was at the beginning I figured that out pretty quickly that way.  And the mini-map makes the objective pretty clear. But somehow the second switch I encountered didn't light up green (I think the light was inside the wall) and I didn't see a door open, but I noticed in the mini-map that the switch did lit up green on it and there was another entrance so I went to check and the door was open. 

Eugene's questions:
1. I thought it was easy and pretty intuitive to hit the switches, it was fun to be able to spam glowy moons all over the place though. Except for the fact that the light wasn't very clear on the 2nd switch (see answer above).

2. Yeah I think it was pretty clear since it stood out from the wall which encourages interaction. 

3. Yes definitely. In the mini-map, the objects (switch + cube) from the upper floor shows up on the lower floor and I tried to spam moons on empty spaces for so long because I thought there HAD to be something there since it was on the mini-map and didn't know there was a 2nd floor yet.

Hazel's questions:
1. I almost used it more than the actual player view... It was easier to navigate the maze through the mini-map than the player view which makes it feel like cheating... maybe if the map didn't rotate with the player it would make the player forced to look at both to direct themselves.

2. Yes, it was clear that the layout changed, I didn't know there was a 2nd floor until my 3rd playthrough though... But maybe that's just me xD

3. Except the fact that objects shows up on both floor and that the outer walls wasn't showing up, I think the mini-map was clear enough. Maybe the icons for switches and collectables could be different to make it more clear.

Questions: 
- Is that is there more than 3 collectables/switches? 
- And was something supposed to happen when you collected the 3 items?

Bugs:
- Sometimes I couldn't collect the cube at all. I don't know if it's a webGL issue but it happened on my first playthrough and it made me confused.
- The contour part of the maze didn't show up on the mini-map and that made it a bit confusing.

**Comment by madslads** [comment]
PlayTester - Madison H.

_Macey's Questions_
- The map was very helpful for navigating the space, the maze was pretty easy to get through. 
- If any of the walls were to stand out to me I would just throw one of the balls at it.

_Eugene's Questions:_
- I didn't find it difficult no, but maybe having the switches be more obvious and clearer, some just seemed like rays of light. Since everything was the same color except for the switches, I always wanted to throw something at anything that could stand out.

_Hazel's Questions_
- I found myself paying most attention to the minimap to help me navigate the space, it made it much easier to locate the switches
- When I switched floors it was apparent that the layout had changed, however the wall colors were not as exciting as the first
- the map was very clear

General Comments:

- The controls are really well done, very smooth and make it easy to navigate the space
- The second maze you get to, felt like it needed more color to the space since the floor and walls were similar colors, maybe some more complex patterns like the first maze
- Perhaps some more platforms to be able to jump onto rather than just a different maze at same level

**Comment by NPhuongHao** [comment]
Macey's Questions
1. Is each section of the map well differentiated enough that you are able to generally situate where you are? --> I originally thought the first floor was symmetrical, but it added a level of needed challenge.

2. How did the hallways feel to navigate? --> I mostly felt like I need to get out of the place ASAP.

3. When you spotted a section of wall that stood out to you, did you think that there was possibly a way in/some way to interact with the scene?

Eugene's Questions:
1. Did you find hitting the switches with the glowing balls easy or difficult? How so? --> I found it quite intuitive and relevant.
2. Did the switches convey to you that you needed to hit them? --> I figured out what I should do mostly because the space is barren, I can through glowing balls and they are the only things glowing, so yes.
3. When you saw something that seemed different or unusual, did you try to throw something at it? --> I threw stuffs at everything, as I was not sure if I can do anything else to the place....

Hazel's Questions:
1. Did you use the minimap to navigate the environment? --> Mainly, yes. I barely look at the real map.
2. When you changed floors, was it clear that the layout had changed? --> Definitely. It took me some sweet time to get to the right path.
3. Was there anything unclear about the map? --> No, I find the map quite relevant.
