### ISSUE TITLE
Team Melissa and Sam: Dog Factory

### ISSUE THREAD

**Issue by miwamiwa** [jdespland-teaching/CART315_2020#19]
Dog Factory

Follow link to play:
https://miwamiwa.github.io/CART315GroupPrototypes/DogFactoryBuild/index.html
( Tested successfully on google chrome, failed on firefox )

Github:
https://github.com/miwamiwa/CART315GroupPrototypes/tree/master/Dog%20Factory

It's panic mode at the dog factory! Dog food, balls and dogs are all being sent to the same room and the struggle is real. Dogs are attracted by balls of their own color, but they are also even more attracted by the dog food. Try to lead the dogs back to their respective boxes by kicking the balls towards them. 
Press WASD to move, Space to jump, P to powermove/kick.
Push the buttons on the platform above to spawn more dogs and balls. 

Questions for playtesters:
- Was there a strategy to your gathering?
- Is it entertaining to observe the dogs' behaviour?
- Did you give up on the goals of gathering the dogs and just spam the buttons?
- Was there not enough or too much dog food?
- Is it too difficult to gather the dogs using the balls? (The kicking not being easy/responsive enough)
- How do you like the color associations, does it help you grasp what is going on?
- Did you try pressing multiple buttons to fill up the room, or did you just press the button once and try to bring the dogs back immediately?
- At what point does the screen seem too full of dogs and balls visually?

**Comment by LastEndConductor** [comment]
- no, I just abused the collision to walk into the dogs and drag them to the boxes.
- no, they were really annoying, randomly deciding when they wanted to chase the balls.
- no, the way to beat the game was not to press any buttons from the start.
- it behaved oddly, sometimes the dogs would actually chase it, other times it disappeared on its own.
- yes, exactly why I just walked into the dogs instead of bothering with the balls.
- nope, I had to come and read the explanation to understand what was going on.
- at first I just pressed buttons, cause you know, BUTTONS, after that I tried to fix the dog situation.
- I haven't pressed the buttons enough for it to get to that point.

**Comment by Cadere** [comment]
1. Not really, I found it more interesting to spam the buttons and frustrating to try and bring the dogs to the boxes.

2. Watching them collide on eachother was entertaining but their behavior was not clear to me. They did not seem to decide to chase the balls or food most of the time.

3. Yes

4. Unsure, the dogs didn't seem to react to it.

5. Yes

6. The colors are fine

7. I tried both. It seems incongruous to me that you choose to bring dogs in when your job is to make the dogs disappear. The dogs should shoot out the cannons and the food come from the buttons.

8. It doesn't, filling the screen is more fun than gathering the dogs.

**Comment by madslads** [comment]
PlayTester - Madison H

_Questions_

1.  I at first created chaos by just pressing every button to see if that would do the job for me
2.  I love observing the dogs, they make me feel less alone in the game
3.  Oh heck yeah, I spammed the buttons to create CHAOS
4.  I didn't really pay attention to how much dog food there was
5.  I felt it was difficult to gather the dogs because at times the kicks felt too powerful
6.  The color associations definitely help with figuring out what's going on
7.  I would always press multiple buttons to fill the room as much as I could
8.  There can never be too much, it doesn't fill up too much
