### ISSUE TITLE
Team ChaNatSol Team Prototype 3

### ISSUE THREAD

**Issue by mortebouse** [jdespland-teaching/CART315_2020#20]
**WebGL build:** https://mortebouse.itch.io/chanatsol-prot-3
**GitHub Repo:** https://github.com/forteller11/CART-315-Team-Prototype-03
**Survey Questions:** 

- How hard was it to understand how the game worked/what you could do? Did you have enough clues given to you?
- How intuitive did it feel to have to use the space bar to perform most functions? Did it feel needlessly inhibiting?
- Does the UI do enough to keep your attention and provide you with information? How effectively did you absorb its content?
- Did you try to push and throw blocks around a lot to see what would happen? What sorts of things did you try?
- How is it, aesthetically? Most importantly, do the animations look nice? Do they look awkward at all?
- Any special comments you’d like to make about your experience playing the game?

**Comment by Harout77** [comment]
1. The instructions were somewhat clear, but hard to execute, for example, the grab/throw, fire wasn't working properly
2. Jumping was working but sometimes, not always you must stand still press a few times the space bar to jump
3. The UI was clear but as I said wasn't working properly as expected.
4. Pushing works smoothly, I really like the 2D collapsable environment.
5. I really liked the aesthetics, the environment was beautiful!

**Comment by Cadere** [comment]
1. It was easy to understand the controls at first, but I never got the "fire" to work and was never able to reach the flame

2. Using the spacebar for most functions was very frustrating, as often I wanted to jump on top of a block or from the top of the block and couldn't because I was interacting with the block instead.

3. The game was very beautiful and the information well presented but I couldn't make the controls work enough to acheive or learn more about the goal.

4. I tried to push blocks around a bit. I didn't succeed at firing them apart from the first one. I tried to jump on top of blocks to reach the flame but couldn't jump from the top of a block because I was interacting with the block instead of jumping.

5. The animations look great and the aesthetic is very beautiful. The colors and pixel art are lovely.

6. Maybe make "W" the jump control and have interactions only with the spacebar.

**Comment by NPhuongHao** [comment]
How hard was it to understand how the game worked/what you could do? Did you have enough clues given to you? --> The instructions are clear and enjoyable, I really love how it was gradually laid out.

How intuitive did it feel to have to use the space bar to perform most functions? Did it feel needlessly inhibiting? --> The controls in general are buggy so I think it's less about the space bar and more about how the player can actually move about. For example, I walked into the ground more than once. 
 
Does the UI do enough to keep your attention and provide you with information? How effectively did you absorb its content? --> My answer is the same in the first question. Very informative and concise.

Did you try to push and throw blocks around a lot to see what would happen? What sorts of things did you try? --> I attempted to, yes. I threw stuffs at stuffs, tried to jump on stuffs, tried to remove stuffs to make my way, but the fact that the controls are quite foreign or maybe buggy made the experience less enjoyable...

How is it, aesthetically? Most importantly, do the animations look nice? Do they look awkward at all? --> I adore the way it looks, everything is so cute.
