### ISSUE TITLE
Team Woe - William and Joe

### ISSUE THREAD

**Issue by Willler** [jdespland-teaching/CART315_2020#22]
**Hi all, here is a link to our first iterative prototype.**

https://joeske.itch.io/iteration-1-team-prototype

The controls are WASD and the left mouse button to shoot. All other keys and mechanics are shown in the game. Please make the game full screen before diving into it or you will not be able to see the game fully.

**Here are our playtest questions:**

**Will's Questions**
a. Were you able to keep track of your score and health while playing? If not, why so? 

b. How well were you able to ascertain what abilities were available to you by looking at UI while playing? 

c. Do you feel like the UI could benefit from indicators other than numbers (such as bars and etc.) 

d. Do you feel like the current amount of information you have available is too much or too little? What else, if anything, would you like to see?

**Comment by LastEndConductor** [comment]
Joe's Questions

1- was the impact of your spells immediately apparent ?

2- were you able to make good use of the spells as you played ?

3- did you notice a break around 10 waves in ? if so, did you notice changes past that break ?

4- did the "sniper" enemies (the ones that went into the corners to track you) feel overwhelming, or too easy ? what changes would you suggest be made to them ?

**Comment by Cadere** [comment]
a. Because of the pace of the game, I was more focussed on my health than on my score.

b. Not that well, I didn't feel like I had time to look at them.

c. I feel like bars for the abilities, with a little pop or glow effect when they get available again, would be beneficial. the number and color was sufficient for the health and score.

d. the amount of available info felt appropriate.

1. Not immediately. I did not understand what the "blank" spell did and the nuke spell would have benefited from some sort of on screen illustration.

2. Not really, but I'm not very good at making use of spells in general. I tend to rely on spamming buttons to get through games. I think I would have if i'd been more spell minded.

3. I did! Ennemies seemed to come more sporadically and in different numbers instead of 4 per wave. Sometimes some would come while there were already others.

4. The sniper enemy was very interesting and I would keep them as is. I think it would be fun however to have yet another type of ennemy, maybe something bigger with a zone attack or something.

**Comment by Harout77** [comment]
1. Yeah, I noticed the score right away by reading the text and learned the health, score and perk systems.
2. It was pretty clear, but if it was displayed in another way it would be better since it's taking gameplay space and it's distracting.
3. It could be a solution to the second question!
4. The amount of information is perfect in my opinion.
