### ISSUE TITLE
TheMuffinWilds: Madison Hunt & Gordon Gray [Intuitive Prototype 1]

### ISSUE THREAD

**Issue by Gmangray4** [jdespland-teaching/CART315_2020#23]
**Link to Game:** 
https://gmangray4.itch.io/dinoeatslecakes

**Link to our team Repository:**
https://github.com/Gmangray4/Cart315-TheMuffinWilds

**Questions:** 

1) What was your highest score? 
2) Do you feel that the game should be longer or shorter? 
3) Have you found any bugs? If so what are they? 
4) What was your favorite thing about this prototype?
5) What did you dislike the most? 
6) Is there anything you would like to see in the next version of this prototype? 
7) Any other commits that you would like to share with us?

**Comment by Cadere** [comment]
1. 60

2. The game lenght was fine to me, though I didn't immediately understand I was timed.

3. The collision detection didn't work super well and often I would feel like i'd run into a cake and not have collided with it.

4. The dino head was fun.

5. How hard it was to actually collide with the cakes, but also how everything was the same color. It took me a very long time to figure out I had an ennemy because I didn't see it well against the landscape.

6. More types of cake, more colors.

**Comment by miwamiwa** [comment]
What was your highest score?
130, 70, 50

Do you feel that the game should be longer or shorter?
The time limit feels a bit short, I think eating cakes extends the time but it doesn't feel like a very significant amount

Have you found any bugs? If so what are they?
Fell through the floor a few times. At first I thought it was a specific spot in the terrain, but on second thought it may happen at a certain slope angle idk

What was your favorite thing about this prototype?
Eating cake yum

What did you dislike the most?
Those pesky cakes are hard to grab! Might be a framerate issue because I'm testing this on a old laptop, but in general I felt like the range at which I could "eat" stuff was rather short. Camera felt a bit jumpy but overall I like the way I could change angles since moving was easier with the cam pointed forward, and eating cake was often easier when looking from above. 

Is there anything you would like to see in the next version of this prototype?
I thought the head was a pretty small concern compared to the time limit. Maybe finding a way to turn that around would be interesting.

Any other commits that you would like to share with us?
Fun stuff! Needs more cake. Yum.
