### ISSUE TITLE
Team Melissa and Samuel Iterative prototype 1

### ISSUE THREAD

**Issue by miwamiwa** [jdespland-teaching/CART315_2020#25]
Balltower v2
by team Melissa and Samuel

In this installment of the new balltower classic the player is once again searching for his dog on a platform filled with balls. 
The player can attempt to locate the dog by whistling and listening out for his barks. They can also collect arrow crates that will temporarily point them towards the doggo. Each time the player reaches the doggo, the platform falls and a new level start with more balls hiding the dog from view. Enjoy!

CONTROLS: WASD to move, SPACE to jump, Q or E to whistle, LEFT CLICK to kick, SHIFT to run

WEBGL LINK:  https://miwamiwa.github.io/CART315GroupPrototypes/Balltower_V2_Build/index.html
GITHUB: https://github.com/miwamiwa/CART315GroupPrototypes/tree/master/Balltower_V2

PLAYTEST QUESTIONS

Are there too many balls? 

The number of new ball spawns increases each level, and old balls are removed once in a while. Did you notice? How do you feel about the progression?
 
Did the fact that the dog moves make it challenging?

Are the arrow crates helpful? Should there be more? Or less, because it's making the search too easy?

Did you jump? Kick? Whistle? Run?

Did you only rely on the barks or on the arrows to search?

Are you interested to see the level number you're at? Should we make it more visible? (Make it a part of UI?)

Are you having trouble with the camera controls?

Any bugs?
Last thoughts?

**Comment by Cadere** [comment]
1. Not at all, the balls and their bouncy noises are the biggest fun and the more the merrier.

2. I noticed that some levels suddenly had less balls than the ones before, which I found a bit confusion. I'm not sure removing the old balls was necessary.

3. Yes! Sometimes I was so close and it ran just past me.

4. They really are! I found the number perfect, I only used them when I wanted to and the arrows didn't last so long as to make too easy.

5. At first I didn't whistle because I didn't realise I could but I went back to test it with it and it was really helpful to get some clues about the dog's whearabouts. I jumped a lot for the same reason (thought it wasn't as helpful as whistling past a certain number of balls) and I didn't really run.

6. I relied on both!

7. I was! At some point I got really far and couldn't see the number anymore because there were too many balls.

8. Yes, a lot. this is my only critique.

**Comment by Harout77** [comment]
1. The balls are proportional to the level and difficulty
2, Yes I noticed the balls increasing.
3. Sometimes, not always, sometimes when I fall down the next level the dog was next to me.
4. Sometimes the crates were useful.
5. Jumping was the way I preferred finding the dog.
6. After level 20 I was using everything, the bark, the crates, the whistle to find the dog.
7.Yes, because after 20 something I couldn't know which level I was at.
8. No,the camera was fine,

**Comment by madslads** [comment]
1)  I thought that the balls added more of an interesting search and find aspect to the game, there 
     weren't too many

2)  I noticed that new balls seemed to appear at each level, and noticed some of the balls disappear 
     when i was wondering around. I thought it was a good progression, not too chaotic

3)  The dogs moving added an extra challenge but I felt that it worked well for the game

4)  I thought that the arrow crates were a cool component of the game, very unique and a good v 
     amount

5) I jumped and whistled, but I felt like using all of the keys was a little difficult to grasp

6) I relied more on the arrows to search as well as just wondering around

7) I thought the level number was clearly visible and didn't really need any more edits

8) Camera controls were pretty good, just wish i would be able to look upwards at times

Final thoughts:
- I didn't notice any bugs except for some strange glitching when the camera would only be moving to one side, overall an easy game to maneuver
