### ISSUE TITLE
Team Macey, Hazel and Eugene's Iterative Prototype 1

### ISSUE THREAD

**Issue by weavingmemories** [jdespland-teaching/CART315_2020#26]
**WEBGL Build Link:**

https://weavingmemories.itch.io/team-iterative-prototype-1

_For some reason, the minimap isn't looking as intended-- it's supposed to be smaller and thinner on the side of the screen. It looks fine in Unity Editor, but in the build, refuses to scale properly._

**Controls:**

- Regular navigation (W A S D controls, mouse to look around, space to jump)
- Left click to throw a light ball. Right click while the ball is mid-air to turn it into a platform.

**Macey's Questions:**

1. How threatening did the rising red liquid seem to you?
2. Was the multiple uses of the same mechanic (using the lights to hit switches as well as create platforms) simple to understand?
3. Did both 'segments' (using platforms inside of the tower to climb, hitting switches and climbing outside of the tower) work well together? Did you prefer one to the other and why?

**Eugene's Questions:**

1. Did you realise that the balls could be used both for making platforms and for hitting switches? How obvious was it?
2. Did the switches convey to you that they could be activated?
3. Where the platforms an efficient way to move around?
4. Did you struggle with the size or angle of the platforms?

**Comment by Willler** [comment]
Hi! I don't see a link to the project repository, so I'll just write my feedback here.

**Macey's Questions**
1. The rising red liquid was a clear indication that I was on a time limit, but it didn't seem to rise quick enough to make me feel much urgency. If it rose a bit faster or made some sound when it got a certain distance from me, I would feel more threatened.
2. The mechanics themselves were simple to understand and they were basic (a good thing, in this case) enough that I was able to experiment pretty quickly.
3. I think they meshed well together. Using platforms was like creating a path to the switches, which were objectives.

**Eugene's Questions**
1. As the balls are the main mechanic, I sort of assumed it would be used for everything.
2. I will admit I didn't realize they were switched right away when looking at them. It's only when I shot a ball at them out of curiosity that it was made clear.
3. I wouldn't necessarily call them "efficient", but the randomness made them more interesting to use. They sometimes put me in situations that I wouldn't have foreseen.
4. The angles felt a bit random to me, but you could jump on pretty steep platforms and still be fine, so it balanced itself pretty well.

Nice work!

**Comment by Gmangray4** [comment]
Macey's Questions:

1) How threatening did the rising red liquid seem to you?

**Very Menacing at first, however once I took the outside route it was not that threatening. Although, when I started to take things slowly, as I was about to reach the top of the tower, I then noticed the Lava got close all of sudden and that spiked my adrenaline. It got threatening when it was right under me.** 

**Other then the above, I later discovered that this rising red liquid you speak of is a lie. After I got outside I tried to see how far out I can move away from the lava, and by that I mean on a horizontal level. I then waited for the Lava to pass by me and I got beneath it! Seeing the lava pass by me from the sides kinda killed the immersion of threatening hot liquid coming to burn me, and after the lava was over my head, I could work my way both up and back all the way down the tower without anything to challenge me.**

**I think you guys could fix this by adding an invisible boundary around the sides of the lava to  punish any players who try to exploit this.**

2) Was the multiple uses of the same mechanic (using the lights to hit switches as well as create platforms) simple to understand?

**No I never understand that there were switches. I was curious if they did anything but I never fired my light bulbs at one. Creating platforms, however, was simple to understand so I spammed that mechanic.** 

3) Did both 'segments' (using platforms inside of the tower to climb, hitting switches and climbing outside of the tower) work well together? Did you prefer one to the other and why?

**I preferred climbing outside, although, I felt like I was outsmarting the level by doing this. I also wondered if I broke the game when I reach the top of the tower from the outside. The game didn't end when I ruched the top so I questioned if the game would have ended if I reached the top of the tower from the inside but I never tried to confirm this. Ultimately, it feels much more challenging to navigate the tower from the inside.**

**There is also this big white looking ceiling near the first outside door; it looked super bright and it blinded me when I was trying to find the first door to the outside on my second run once.** 

Eugene's Questions:

1) Did you realise that the balls could be used both for making platforms and for hitting switches? How obvious was it?

**No, unfortunately I didn't notice you could use the balls to hit switches. I was wondering what they did but never thought of shooting them with the light bulbs. Ultimately, in the end I use the switches. as platforms.**

2) Did the switches convey to you that they could be activated?

**No sadly.** 

3) Where the platforms an efficient way to move around?

**Inside of the tower it's less efficient but once you get outside of the tower that's where it's way too effectively easy to move around: This is because you have more open space outdoors to create platforms then you do inside the tower. so if you miss up in one area you could find another empty space to make another set of platforms that work in your favor then when indoors. Indoors you have less space to work with so there is more of a chance that the platforms will pile up and work against you then with you.** 

4) Did you struggle with the size or angle of the platforms?

**The size no the angles sometimes yes as they are random, however, once I got the hang of using them I could effectively climb the entire tower with no problem. my main strategy was to bundle up a bunch of Platforms in one spot then jump on top of them. it was very effective but that's only because I was outside the tower with a ton of open space to use.**
