### ISSUE TITLE
Team ChaNatSol Iterative Prototype 1

### ISSUE THREAD

**Issue by mortebouse** [jdespland-teaching/CART315_2020#27]
**WebGL build:** https://mortebouse.itch.io/team-chanatsol-iterative-prot-1
**GitHub Repo:** https://github.com/forteller11/CART-315-Team-Prototype-03
**Survey Questions:** 

- What’s your opinion of the level design? Do you feel like things were set up in such a way that you could figure out how to exit the dungeon in a manner that was challenging yet not too frustrating?
- When it came to opening the door in the dungeon’s ceiling, would you say the clue hidden in the parallax background helped you figure out which object you needed to throw over to the other side of the room?
- Do you feel like the level’s puzzle took full advantage of the game’s mechanics? Why/Why not?
- Is the level too long? Too short?
- What’s your opinion on the size of the level?
- Do you notice anything that seems like a bug? Did these inhibit your experience? 
- Any special comments you’d like to make about your experience playing the game?

**Comment by Cadere** [comment]
1. I think I figured out how to exit the dungeon, but throwing a block in the last well, but I was not able to do it because they kept falling into the other wells and I couldn't get them out. I found this frustrating.

2. I did not notice the clue.

3. I think the mechanics are doing a disservice to the level, as I was still sometimes struggling between jumping and grabbing when i was close to a block. having both controls on the spacebar feels restrictive and adds to the difficulty but not the satisfaction. I also feel it should be clearer when i block is grabbed or not. I did not understand what determined the strenght with which a block was thrown.

4. The level's size seemed appropriate but the camera seemed to high or too slow to follow the character.
 
5. There was no killbox under the wells that exited the map and I just kept falling out of the level and had to close and reload the game to try again.

6. The aestetic is very pretty, but unfortunately the controls are annoying and there are too many ways to get stuck in the level (falling off, all the blocks stuck in a well) and no way to restart in-game.

**Comment by miwamiwa** [comment]
1. Very nice visual design but I didn't really understand the puzzle given the initial instructions. Did not manage much other than falling out of the dungeon. I tried hurling boxes around, dumping them in holes, thought maybe I should assemble them together but I could get more than 2 together. Feel like I'm missing the point.
2. Didn't see the clue or a door
3. Hard to say if I was engaging with the puzzle. 
4. Can't really say
5. Size felt fine. I second the comment above, the camera follow is a bit slow when you are moving back down after jumping. 
6. There is no way to run right away after jumping, there is always a pause. 
Some kind of visual feedback for when I successfully grab an object would be nice. 
7. Game looks nice but I find it too bad I can't figure it out. I feel like I need a bit more instructions at the beginning, or some feedback that tells me that i'm doing things right. If the goal is to avoid giving too many clues away, then maybe simple sounds could tell me that something's worked, without giving away what worked or how, etc. If you want you could give me some clues and I would test again with those in mind, since I'm not convinced I managed to address all the questions that well.

**Comment by Harout77** [comment]
1. the level design is nice and beautiful, but couldn't find the exit, maybe hints on what I must do could help a bit.
2. I did not notice anything so can't tell but the parallax was nice.
3. The level was short maybe because I didn't know what to do.
4. Did not find any bug but sometimes the jumping was sticky.
