### ISSUE TITLE
Team Harout Iterative Prototype 1

### ISSUE THREAD

**Issue by Harout77** [jdespland-teaching/CART315_2020#28]
**GitHub Repo link**

- https://github.com/Harout77/CART315_HaroutKullukian/tree/master/Iterative%20prototype%201

**Itch.io link  (Must play in full screen by pressing the blue button)**

- https://serharout.itch.io/untitled    

**Playtesting Question**

- If you could choose a third character to play as, who/ what will it be?
- Is the difficulty too easy, too hard or just normal?
- If you could add a new power-up what would it be? (currently, there are move faster, slower, go big, go small)
- Any new ideas, comments, suggestions?

**Comment by Cadere** [comment]
1. A triangle
2. I always felt like I was going a bit too fast but the difficulty was fine. Controls are much much smoother than last week, congrats! It's really nice that we can jump now, though I feel the jump is too high / far.
3. When i played it seemed yellow powerups were smaller&faster and purple powerups were slower&bigger most of the time? if not it would be easier to tell the difference if there were 4 colors of powerups. Go slower and smaller powerups were the ones I was seeking. Maybe if the basic jump was smaller, there could be a bigger jump powerup.
4. I would have loved to have some ramps or geography that wasn't an obstacle/killbox. Getting spun around as the cube was fun and I wish it didn't mean I died.

**Comment by miwamiwa** [comment]
1. I agree with the triangle idea above, it's fun watching the physics bounce the square around
2. Difficulty seemed fine to me! Still a challenge but it feels much more accessible this time. 
3. Temporary invincibility? I wasn't too sure what the red gem does by the way, as I was playing I thought it may be nice if text popped out that tells you what the powerup is.
4. Love the feel of the game, with the different sound and visual thematics. 
To save some time I eventually just jumped my way to the end screen. You can avoid most of the game by letting yourself fall to the side then jumping really far ahead. It's clearly not the way to play but it might be nice to prevent that somehow. Anyway it allowed me to see and hear the whole game, which I really enjoyed.
Would be nice for the music to continue when you die instead of restarting!

**Comment by madslads** [comment]
1. Maybe adding a customized third character would be an interesting add on for the game 
2. It seems the character moved very fast as times and made it hard to dodge objects, maybe having it start of slower then get faster as the game progresses would make it a bit easier
3. Having a power-up where you are able to destroy 2-3 objects that you may accidentally run into would make the game a bit more exciting i think
4. The game was pretty fun, just felt very fast at times, great design
