### ISSUE TITLE
Team Alex and Hao

### ISSUE THREAD

**Issue by Nomad29** [jdespland-teaching/CART315_2020#9]
I'm a teammate, my GitHub will host the prototypes.
Team composition: Alexandra Melançon and Hao Phuong Nguyen

**Comment by NPhuongHao** [comment]
coming innnn

**Comment by NPhuongHao** [comment]
Issue 1: Apply continuous movement on the player character (in order to turn it into a snake). If continuous movement is not on then the tail update becomes a royal mess..................

Current state using the old navigation control in Alex's prototype.
https://github.com/Nomad29/cart315-2020-teamproject/commits/master

Possible solution (note for when I'm actually awake and sober to implement it): change how x and z work in Move()? For now, it depends on whether or not a key input is active, so maybe blend them with the Direction detection from my prototype? (Ex: if playerDirection == left then x = -1 * Time.deltaTime * speed; z = 0????)

**Comment by NPhuongHao** [comment]
[ISSUES SOLVED]
